port: 8080
addr: 127.0.0.1
env: development
url: "http://kitsquid.example.com"

tls:
  enable: false
  key: etc/key.pem
  cert: etc/cert.pem

db:
  path: kitsquid.db
  encoding: gob # json or gob

mail:
  from: mail@example.com
  smtp:
    host: mail.example.com
    port: 25
    user: mail@example.com
    password: "shhh"

cache:
  lectures: 30m
  misc: 60m
  users: 60m
  sessions: 10m
  bookmarks: 30m
  comments: 30m
  reviews: 30m

auth:
  salt: ssshhh
  session:
    timeout: 168h # 7d
  admins:
    - "admin@example.com"
  whitelist:
    - prefix-pattern: ^u[\w]{4}
      prefix-display: uxxxx
      suffix-pattern: \@student.kit.edu$
      suffix-display: student.kit.edu

university:
  degrees:
    - Bachelor
    - Master
    - Sonstiges

  genders:
    - Männlich
    - Weiblich
    - Divers

  majors:
    - Altbauinstandsetzung
    - Angewandte Geowissenschaften
    - Architektur
    - Bauingenieurwesen
    - Bioingenieurwesen
    - Biologie
    - Biologie Lehramt
    - Chemie
    - Chemie Lehramt
    - Chemieingenieurwesen und Verfahrenstechnik
    - Chemische Biologie
    - Deutsch Lehramt
    - Elektrotechnik und Informationstechnik
    - Energy Engineering and Management
    - Europäische Kultur- und Ideengeschichte
    - Financial Engineering
    - Funktionaler und konstruktiver Ingenieurbau - Engineering Structures
    - Geographie Lehramt
    - Geodäsie und Geoinformatik
    - Geoökologie
    - Geophysik
    - Germanistik
    - Informatik
    - Informatik Lehramt
    - Information Systems Engineering and Management
    - Ingenieurpädagogik
    - Ingenieurpädagogik für Ingenieurinnen und Ingenieure
    - Kunstgeschichte
    - Lebensmittelchemie
    - Management of Product Development
    - Maschinenbau
    - Materialwissenschaft und Werkstofftechnik
    - Mathematik
    - Mathematik Lehramt
    - Mechanical Engineering International
    - Mechatronik und Informationstechnik
    - Meteorologie
    - Mobilität und Infrastruktur
    - Mobility Systems Engineering and Management
    - Naturwissenschaft und Technik Lehramt
    - Optics and Photonics
    - Pädagogik
    - Philosophie / Ethik Lehramt
    - Physik
    - Physik Lehramt
    - Production and Operations Management
    - Regionalwissenschaft / Raumplanung
    - Remote Sensing and Geoinformatics
    - Sport Lehramt
    - Sportwissenschaft
    - Technische Volkswirtschaftslehre
    - Technomathematik
    - Water Science Engineering
    - Wirtschaftsinformatik
    - Wirtschaftsingenieurwesen
    - Wirtschaftsmathematik
    - Wissenschaft - Medien - Kommunikation